package com.pfe.persistance;

// Generated 29 févr. 2016 10:37:19 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Personnel generated by hbm2java
 */
public class Personnel implements java.io.Serializable {

	private Integer matricule;
	private Compte compte;
	private String nomPer;
	private String prenomPer;
	private Integer telephone;
	private String cin;
	private Date dateNaissance;
	private String email;
	private Set<Compte> comptes = new HashSet<Compte>(0);

	public Personnel() {
	}

	public Personnel(Compte compte, String nomPer, String prenomPer,
			Integer telephone, String cin, Date dateNaissance, String email,
			Set<Compte> comptes) {
		this.compte = compte;
		this.nomPer = nomPer;
		this.prenomPer = prenomPer;
		this.telephone = telephone;
		this.cin = cin;
		this.dateNaissance = dateNaissance;
		this.email = email;
		this.comptes = comptes;
	}

	public Integer getMatricule() {
		return this.matricule;
	}

	public void setMatricule(Integer matricule) {
		this.matricule = matricule;
	}

	public Compte getCompte() {
		return this.compte;
	}

	public void setCompte(Compte compte) {
		this.compte = compte;
	}

	public String getNomPer() {
		return this.nomPer;
	}

	public void setNomPer(String nomPer) {
		this.nomPer = nomPer;
	}

	public String getPrenomPer() {
		return this.prenomPer;
	}

	public void setPrenomPer(String prenomPer) {
		this.prenomPer = prenomPer;
	}

	public Integer getTelephone() {
		return this.telephone;
	}

	public void setTelephone(Integer telephone) {
		this.telephone = telephone;
	}

	public String getCin() {
		return this.cin;
	}

	public void setCin(String cin) {
		this.cin = cin;
	}

	public Date getDateNaissance() {
		return this.dateNaissance;
	}

	public void setDateNaissance(Date dateNaissance) {
		this.dateNaissance = dateNaissance;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Set<Compte> getComptes() {
		return this.comptes;
	}

	public void setComptes(Set<Compte> comptes) {
		this.comptes = comptes;
	}

}
