package com.pfe.persistance;

// Generated 20 mars 2016 18:33:48 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Categorie generated by hbm2java
 */
public class Categorie implements java.io.Serializable {

	private Integer numeroCategorie;
	private String nomCategorie;
	private String typeCategorie;
	private Set<Vehicule> vehicules = new HashSet<Vehicule>(0);

	public Categorie() {
	}

	public Categorie(String nomCategorie, String typeCategorie,
			Set<Vehicule> vehicules) {
		this.nomCategorie = nomCategorie;
		this.typeCategorie = typeCategorie;
		this.vehicules = vehicules;
	}

	public Integer getNumeroCategorie() {
		return this.numeroCategorie;
	}

	public void setNumeroCategorie(Integer numeroCategorie) {
		this.numeroCategorie = numeroCategorie;
	}

	public String getNomCategorie() {
		return this.nomCategorie;
	}

	public void setNomCategorie(String nomCategorie) {
		this.nomCategorie = nomCategorie;
	}

	public String getTypeCategorie() {
		return this.typeCategorie;
	}

	public void setTypeCategorie(String typeCategorie) {
		this.typeCategorie = typeCategorie;
	}

	public Set<Vehicule> getVehicules() {
		return this.vehicules;
	}

	public void setVehicules(Set<Vehicule> vehicules) {
		this.vehicules = vehicules;
	}

}
