package com.pfe.persistance;

// Generated 20 mars 2016 18:33:48 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Etat generated by hbm2java
 */
public class Etat implements java.io.Serializable {

	private Integer numeroEtat;
	private String nomEtat;
	private Set<Vehicule> vehicules = new HashSet<Vehicule>(0);

	public Etat() {
	}

	public Etat(String nomEtat, Set<Vehicule> vehicules) {
		this.nomEtat = nomEtat;
		this.vehicules = vehicules;
	}

	public Integer getNumeroEtat() {
		return this.numeroEtat;
	}

	public void setNumeroEtat(Integer numeroEtat) {
		this.numeroEtat = numeroEtat;
	}

	public String getNomEtat() {
		return this.nomEtat;
	}

	public void setNomEtat(String nomEtat) {
		this.nomEtat = nomEtat;
	}

	public Set<Vehicule> getVehicules() {
		return this.vehicules;
	}

	public void setVehicules(Set<Vehicule> vehicules) {
		this.vehicules = vehicules;
	}

}
