package com.pfe.persistance;

// Generated 20 mars 2016 18:33:48 by Hibernate Tools 3.4.0.CR1

/**
 * Marque generated by hbm2java
 */
public class Marque implements java.io.Serializable {

	private Integer numeroMarque;
	private Modele modele;
	private String nomMarque;

	public Marque() {
	}

	public Marque(Modele modele, String nomMarque) {
		this.modele = modele;
		this.nomMarque = nomMarque;
	}

	public Integer getNumeroMarque() {
		return this.numeroMarque;
	}

	public void setNumeroMarque(Integer numeroMarque) {
		this.numeroMarque = numeroMarque;
	}

	public Modele getModele() {
		return this.modele;
	}

	public void setModele(Modele modele) {
		this.modele = modele;
	}

	public String getNomMarque() {
		return this.nomMarque;
	}

	public void setNomMarque(String nomMarque) {
		this.nomMarque = nomMarque;
	}

}
