package com.pfe.persistance;

// Generated 20 mars 2016 18:33:48 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Mecanicien generated by hbm2java
 */
public class Mecanicien implements java.io.Serializable {

	private Integer numeroMecanicien;
	private Entretien entretien;
	private String nomMecanicien;
	private String adresse;
	private Integer telephone;
	private Set<Entretien> entretiens = new HashSet<Entretien>(0);

	public Mecanicien() {
	}

	public Mecanicien(Entretien entretien, String nomMecanicien,
			String adresse, Integer telephone, Set<Entretien> entretiens) {
		this.entretien = entretien;
		this.nomMecanicien = nomMecanicien;
		this.adresse = adresse;
		this.telephone = telephone;
		this.entretiens = entretiens;
	}

	public Integer getNumeroMecanicien() {
		return this.numeroMecanicien;
	}

	public void setNumeroMecanicien(Integer numeroMecanicien) {
		this.numeroMecanicien = numeroMecanicien;
	}

	public Entretien getEntretien() {
		return this.entretien;
	}

	public void setEntretien(Entretien entretien) {
		this.entretien = entretien;
	}

	public String getNomMecanicien() {
		return this.nomMecanicien;
	}

	public void setNomMecanicien(String nomMecanicien) {
		this.nomMecanicien = nomMecanicien;
	}

	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	public Integer getTelephone() {
		return this.telephone;
	}

	public void setTelephone(Integer telephone) {
		this.telephone = telephone;
	}

	public Set<Entretien> getEntretiens() {
		return this.entretiens;
	}

	public void setEntretiens(Set<Entretien> entretiens) {
		this.entretiens = entretiens;
	}

}
