package com.pfe.persistance;

// Generated 20 mars 2016 18:33:48 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Personnel generated by hbm2java
 */
public class Personnel implements java.io.Serializable {

	private Integer matricule;
	private Ville ville;
	private Departement departement;
	private Typepersonnel typepersonnel;
	private Service service;
	private String nom;
	private String prenom;
	private String cin;
	private String telephone;
	private Date dateNaissance;
	private String adresse;
	private String email;
	private String numeroTel1;
	private String numeroTel2;
	private Set<Reclamation> reclamations = new HashSet<Reclamation>(0);
	private Compte compte;

	public Personnel() {
	}

	public Personnel(Ville ville, Departement departement,
			Typepersonnel typepersonnel, Service service, String nom,
			String prenom, String cin, String telephone, Date dateNaissance,
			String adresse, String email, String numeroTel1, String numeroTel2,
			Set<Reclamation> reclamations, Compte compte) {
		this.ville = ville;
		this.departement = departement;
		this.typepersonnel = typepersonnel;
		this.service = service;
		this.nom = nom;
		this.prenom = prenom;
		this.cin = cin;
		this.telephone = telephone;
		this.dateNaissance = dateNaissance;
		this.adresse = adresse;
		this.email = email;
		this.numeroTel1 = numeroTel1;
		this.numeroTel2 = numeroTel2;
		this.reclamations = reclamations;
		this.compte = compte;
	}

	public Integer getMatricule() {
		return this.matricule;
	}

	public void setMatricule(Integer matricule) {
		this.matricule = matricule;
	}

	public Ville getVille() {
		return this.ville;
	}

	public void setVille(Ville ville) {
		this.ville = ville;
	}

	public Departement getDepartement() {
		return this.departement;
	}

	public void setDepartement(Departement departement) {
		this.departement = departement;
	}

	public Typepersonnel getTypepersonnel() {
		return this.typepersonnel;
	}

	public void setTypepersonnel(Typepersonnel typepersonnel) {
		this.typepersonnel = typepersonnel;
	}

	public Service getService() {
		return this.service;
	}

	public void setService(Service service) {
		this.service = service;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	public String getCin() {
		return this.cin;
	}

	public void setCin(String cin) {
		this.cin = cin;
	}

	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public Date getDateNaissance() {
		return this.dateNaissance;
	}

	public void setDateNaissance(Date dateNaissance) {
		this.dateNaissance = dateNaissance;
	}

	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getNumeroTel1() {
		return this.numeroTel1;
	}

	public void setNumeroTel1(String numeroTel1) {
		this.numeroTel1 = numeroTel1;
	}

	public String getNumeroTel2() {
		return this.numeroTel2;
	}

	public void setNumeroTel2(String numeroTel2) {
		this.numeroTel2 = numeroTel2;
	}

	public Set<Reclamation> getReclamations() {
		return this.reclamations;
	}

	public void setReclamations(Set<Reclamation> reclamations) {
		this.reclamations = reclamations;
	}

	public Compte getCompte() {
		return this.compte;
	}

	public void setCompte(Compte compte) {
		this.compte = compte;
	}

}
