package com.pfe.persistance;

// Generated 20 mars 2016 18:33:48 by Hibernate Tools 3.4.0.CR1

/**
 * Vehicule generated by hbm2java
 */
public class Vehicule implements java.io.Serializable {

	private Integer immatricule;
	private Categorie categorie;
	private Etat etat;
	private Integer nombrePlace;
	private String puissance;
	private Integer kelometrage;
	private Integer capaciteBagage;

	public Vehicule() {
	}

	public Vehicule(Categorie categorie, Etat etat, Integer nombrePlace,
			String puissance, Integer kelometrage, Integer capaciteBagage) {
		this.categorie = categorie;
		this.etat = etat;
		this.nombrePlace = nombrePlace;
		this.puissance = puissance;
		this.kelometrage = kelometrage;
		this.capaciteBagage = capaciteBagage;
	}

	public Integer getImmatricule() {
		return this.immatricule;
	}

	public void setImmatricule(Integer immatricule) {
		this.immatricule = immatricule;
	}

	public Categorie getCategorie() {
		return this.categorie;
	}

	public void setCategorie(Categorie categorie) {
		this.categorie = categorie;
	}

	public Etat getEtat() {
		return this.etat;
	}

	public void setEtat(Etat etat) {
		this.etat = etat;
	}

	public Integer getNombrePlace() {
		return this.nombrePlace;
	}

	public void setNombrePlace(Integer nombrePlace) {
		this.nombrePlace = nombrePlace;
	}

	public String getPuissance() {
		return this.puissance;
	}

	public void setPuissance(String puissance) {
		this.puissance = puissance;
	}

	public Integer getKelometrage() {
		return this.kelometrage;
	}

	public void setKelometrage(Integer kelometrage) {
		this.kelometrage = kelometrage;
	}

	public Integer getCapaciteBagage() {
		return this.capaciteBagage;
	}

	public void setCapaciteBagage(Integer capaciteBagage) {
		this.capaciteBagage = capaciteBagage;
	}

}
