package com.pfe.persistance;

// Generated 20 mars 2016 18:33:48 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Vignette generated by hbm2java
 */
public class Vignette implements java.io.Serializable {

	private Integer numeroVignette;
	private Date dateDebut;
	private Float montant;
	private Date dateFin;

	public Vignette() {
	}

	public Vignette(Date dateDebut, Float montant, Date dateFin) {
		this.dateDebut = dateDebut;
		this.montant = montant;
		this.dateFin = dateFin;
	}

	public Integer getNumeroVignette() {
		return this.numeroVignette;
	}

	public void setNumeroVignette(Integer numeroVignette) {
		this.numeroVignette = numeroVignette;
	}

	public Date getDateDebut() {
		return this.dateDebut;
	}

	public void setDateDebut(Date dateDebut) {
		this.dateDebut = dateDebut;
	}

	public Float getMontant() {
		return this.montant;
	}

	public void setMontant(Float montant) {
		this.montant = montant;
	}

	public Date getDateFin() {
		return this.dateFin;
	}

	public void setDateFin(Date dateFin) {
		this.dateFin = dateFin;
	}

}
