package com.pfe.persistance;

// Generated 28 févr. 2016 18:08:45 by Hibernate Tools 3.4.0.CR1


/**
 * Compte generated by hbm2java
 */
public class Compte {

	private Integer matricule;
	private Personnel personnel;
	private String login;
	private String motDePasse;


	public Compte() {
	}


	public Integer getMatricule() {
		return matricule;
	}


	public void setMatricule(Integer matricule) {
		this.matricule = matricule;
	}


	public Personnel getPersonnel() {
		return personnel;
	}


	public void setPersonnel(Personnel personnel) {
		this.personnel = personnel;
	}


	public String getLogin() {
		return login;
	}


	public void setLogin(String login) {
		this.login = login;
	}


	public String getMotDePasse() {
		return motDePasse;
	}


	public void setMotDePasse(String motDePasse) {
		this.motDePasse = motDePasse;
	}


	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((login == null) ? 0 : login.hashCode());
		result = prime * result
				+ ((matricule == null) ? 0 : matricule.hashCode());
		result = prime * result
				+ ((motDePasse == null) ? 0 : motDePasse.hashCode());
		return result;
	}


	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Compte other = (Compte) obj;
		if (login == null) {
			if (other.login != null)
				return false;
		} else if (!login.equals(other.login))
			return false;
		if (matricule == null) {
			if (other.matricule != null)
				return false;
		} else if (!matricule.equals(other.matricule))
			return false;
		if (motDePasse == null) {
			if (other.motDePasse != null)
				return false;
		} else if (!motDePasse.equals(other.motDePasse))
			return false;
		return true;
	}

	

}
