package com.pfe.persistance;

// Generated 28 févr. 2016 18:08:45 by Hibernate Tools 3.4.0.CR1


/**
 * Compte generated by hbm2java
 */
public class Compte {

	private Integer matricule;
	private Personnel personnel;
	private String login;
	private String mot_de_passe;


	public Compte() {
	}


	public Integer getMatricule() {
		return matricule;
	}


	public void setMatricule(Integer matricule) {
		this.matricule = matricule;
	}


	public Personnel getPersonnel() {
		return personnel;
	}


	public void setPersonnel(Personnel personnel) {
		this.personnel = personnel;
	}


	public String getLogin() {
		return login;
	}


	public void setLogin(String login) {
		this.login = login;
	}


	public String getmot_de_passe() {
		return mot_de_passe;
	}


	public void setmot_de_passe(String mot_de_passe) {
		this.mot_de_passe = mot_de_passe;
	}


	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((login == null) ? 0 : login.hashCode());
		result = prime * result
				+ ((matricule == null) ? 0 : matricule.hashCode());
		result = prime * result
				+ ((mot_de_passe == null) ? 0 : mot_de_passe.hashCode());
		return result;
	}


	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Compte other = (Compte) obj;
		if (login == null) {
			if (other.login != null)
				return false;
		} else if (!login.equals(other.login))
			return false;
		if (matricule == null) {
			if (other.matricule != null)
				return false;
		} else if (!matricule.equals(other.matricule))
			return false;
		if (mot_de_passe == null) {
			if (other.mot_de_passe != null)
				return false;
		} else if (!mot_de_passe.equals(other.mot_de_passe))
			return false;
		return true;
	}

	

}
